// <auto-generated />
using FDFLodsedler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FDFLodsedler.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231207094851_Initail")]
    partial class Initail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FDFLodsedler.Model.Bestyrelse", b =>
                {
                    b.Property<int>("Bestyrelse_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bestyrelse_Id"), 1L, 1);

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Bestyrelse_Id");

                    b.ToTable("Bestyrelses");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Betaling", b =>
                {
                    b.Property<int>("Betal_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Betal_Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Betal_Id");

                    b.ToTable("Betalings");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Børn", b =>
                {
                    b.Property<int>("Børn_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Børn_Id"), 1L, 1);

                    b.Property<int>("Gruppe_Id")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Børn_Id");

                    b.HasIndex("Gruppe_Id");

                    b.ToTable("Børns");
                });

            modelBuilder.Entity("FDFLodsedler.Model.BørneGruppe", b =>
                {
                    b.Property<int>("Gruppe_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gruppe_Id"), 1L, 1);

                    b.Property<int>("Leder_Id")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Gruppe_Id");

                    b.HasIndex("Leder_Id");

                    b.ToTable("BørnGruppes");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Leder", b =>
                {
                    b.Property<int>("Leder_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Leder_Id"), 1L, 1);

                    b.Property<string>("BrugerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Leder_Id");

                    b.ToTable("Leders");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Lodseldler", b =>
                {
                    b.Property<int>("Lod_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lod_Id"), 1L, 1);

                    b.Property<int>("AntalUdleveret")
                        .HasColumnType("int");

                    b.Property<int>("Børn_Id")
                        .HasColumnType("int");

                    b.HasKey("Lod_Id");

                    b.HasIndex("Børn_Id");

                    b.ToTable("Lodsedlers");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Salg", b =>
                {
                    b.Property<int>("Salg_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Salg_Id"), 1L, 1);

                    b.Property<int>("AntalReturneret")
                        .HasColumnType("int");

                    b.Property<int>("AntalSolgt")
                        .HasColumnType("int");

                    b.Property<int>("Børn_Id")
                        .HasColumnType("int");

                    b.HasKey("Salg_Id");

                    b.HasIndex("Børn_Id");

                    b.ToTable("Salgs");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Børn", b =>
                {
                    b.HasOne("FDFLodsedler.Model.BørneGruppe", "BørneGruppe")
                        .WithMany()
                        .HasForeignKey("Gruppe_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BørneGruppe");
                });

            modelBuilder.Entity("FDFLodsedler.Model.BørneGruppe", b =>
                {
                    b.HasOne("FDFLodsedler.Model.Leder", "Leder")
                        .WithMany()
                        .HasForeignKey("Leder_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leder");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Lodseldler", b =>
                {
                    b.HasOne("FDFLodsedler.Model.Børn", "Børn")
                        .WithMany()
                        .HasForeignKey("Børn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Børn");
                });

            modelBuilder.Entity("FDFLodsedler.Model.Salg", b =>
                {
                    b.HasOne("FDFLodsedler.Model.Børn", "Børn")
                        .WithMany()
                        .HasForeignKey("Børn_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Børn");
                });
#pragma warning restore 612, 618
        }
    }
}
